---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-checkup-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-checkup-result
  namespace: echo-checkup-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-checkup-sa
  namespace: echo-checkup-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-patcher
  namespace: echo-checkup-ns
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "patch" ]
    resourceNames: ["echo-checkup-result"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-patcher-echo-checkup-sa
  namespace: echo-checkup-ns
subjects:
  - kind: ServiceAccount
    name: echo-checkup-sa
    namespace: echo-checkup-ns
roleRef:
  kind: Role
  name: configmap-patcher
  apiGroup: rbac.authorization.k8s.io
...
