apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-latency-check-config
  namespace: default
data:
  RESULT_CM_NAMESPACE: "default"
  RESULT_CM_NAME: "kubevirt-latency-check-config"
  NETWORK_NAMESPACE: "default"
  NETWORK_NAME: "sriov-network"
  DURATION: "10s"
  SOURCE_NODE: "sriov-worker"
  TARGET_NODE: "sriov-worker"
