apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodes-reader-to-framework-sa
subjects:
- kind: ServiceAccount
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: nodes-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirts-reader-to-framework-sa
subjects:
- kind: ServiceAccount
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kubevirts-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: networks-reader-to-framework-sa
subjects:
- kind: ServiceAccount
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: networks-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-vmis-manager-to-framework-sa
subjects:
- kind: ServiceAccount
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kubevirt-vmis-manager


