---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirts-reader-to-sa
subjects:
  - kind: ServiceAccount
    name: kubevirt-latency-checker
    namespace: kubevirt-latency-check
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kubevirts-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-vmi-manager-to-sa
  namespace: kubevirt-latency-check
subjects:
  - kind: ServiceAccount
    name: kubevirt-latency-checker
    namespace: kubevirt-latency-check
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kubevirt-vmi-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-reader-to-sa
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubevirt-latency-checker
    namespace: kubevirt-latency-check
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: network-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
  namespace: kubevirt-latency-check
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-to-sa
  namespace: kubevirt-latency-check
subjects:
- kind: ServiceAccount
  name: kubevirt-latency-checker
  namespace: kubevirt-latency-check
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: configmap-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-writer
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: result-configmap-writer-to-sa
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubevirt-latency-checker
  namespace: kubevirt-latency-check
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: configmap-writer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: latencycheck
  namespace: kubevirt-latency-check
spec:
  ttlSecondsAfterFinished: 216000
  backoffLimit: 0
  template:
    spec:
      restartPolicy: "Never"
      terminationGracePeriodSeconds: 5
      serviceAccount: kubevirt-latency-checker
      containers:
      - name: latencycheck
        resources:
          limits:
            memory: "50Mi"
            cpu: "1" 
          requests:
            memory: "50Mi"
            cpu: "1" 
        image: "registry:5000/kubevirt-latency-check:latest"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: kubevirt-latency-check-config
