---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-checkup-framework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-to-checkup-framework-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: checkup-framework-sa
  namespace: k8s-checkup-framework