---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-checkup-framework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkup-launcher-sa
  namespace: k8s-checkup-framework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
  namespace: k8s-checkup-framework
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-checkup-launcher-sa
  namespace: k8s-checkup-framework
subjects:
  - kind: ServiceAccount
    name: checkup-launcher-sa
    namespace: k8s-checkup-framework
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
...
