---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-checkup-framework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
  namespace: k8s-checkup-framework
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-checkup-framework-sa
  namespace: k8s-checkup-framework
subjects:
  - kind: ServiceAccount
    name: checkup-framework-sa
    namespace: k8s-checkup-framework
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkup-framework
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get", "list", "create" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "create", "update", "patch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings" ]
    verbs: [ "get", "list", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkup-framework-checkup-framework-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkup-framework
subjects:
  - kind: ServiceAccount
    name: checkup-framework-sa
    namespace: k8s-checkup-framework
...
