---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-checkup-framework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkup-framework
rules:
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs:
  - get
  - list
  - create
- apiGroups: [ "" ]
  resources: [ "serviceaccounts" ]
  verbs:
  - get
  - list
  - create
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups: [ "rbac.authorization.k8s.io" ]
  resources:
  - roles
  - clusterroles
  - rolebindings
  - clusterrolebindings
  verbs:
  - get
  - list
  - create
- apiGroups: [ "batch" ]
  resources: [ "jobs" ]
  verbs:
  - get
  - list
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkup-framework-to-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkup-framework
subjects:
- kind: ServiceAccount
  name: checkup-framework-sa
  namespace: k8s-checkup-framework
    Add framework e2e automation script
    
    Currently there is no automation for running
    a checkup through the framework including building
    the images of the framework and the checkup.
    
    In order to shorten iteration time and get quick
    feedback whether this commit introduce hack/framework-e2e
    which automate the following flow:
    - checkup-framework build
    - echo checkup build
    - framework deployment
    - running the echo checkup with the framework
    - teardown

    Also, echo checkup build-image script is changed
    to enable running it from any directory.
